name: AMI Builder
description: Build and validate AMIs (via Packer)
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  task:
    description: The specific task to run (validate, build, verify, share-with-org)
    required: true
  ami-id:
    description: The AMI ID to verify after creation
    required: false
outputs:
  ami-id:
    description: The ID of the generated AMI
